apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-streamlit
  template:
    metadata:
      labels:
        app: iris-streamlit
    spec:
      containers:
      - name: streamlit
        image: registry.gitlab.com/aryansr/mykubeflow/iris-streamlit:1.0
        envFrom:
        - configMapRef:
            name: iris-streamlit-config
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: iris-streamlit
spec:
  selector:
    app: iris-streamlit
  ports:
  - port: 80
    targetPort: 8501
