
# 1. PushGateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: kubeflow
  labels:
    app: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: prom/pushgateway:latest
        ports:
        - containerPort: 9091
---
# 2. PushGateway Service
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: kubeflow
spec:
  selector:
    app: pushgateway
  ports:
  - port: 9091
    targetPort: 9091
---
# 3. Prometheus ConfigMap (minimal prometheus.yml)
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kubeflow
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'pushgateway'
        static_configs:
          - targets: ['pushgateway.kubeflow.svc.cluster.local:9091']
---
# 4. Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: kubeflow
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: data
          mountPath: /prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      - name: data
        emptyDir: {}
---
# 5. Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kubeflow
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
