apiVersion: v1
kind: Pod
metadata:
  name: pvc-loader
  namespace: kubeflow-user-example-com   # <-- change as needed
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: docker-pull
  containers:
    - name: loader
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: train-data
          mountPath: /data
  volumes:
    - name: train-data
      persistentVolumeClaim:
        claimName: llm-train-pvc
