FROM python:3.8-slim

WORKDIR /app

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Streamlit app
COPY streamlit_app.py /app/streamlit_app.py

# Expose Streamlit port
EXPOSE 8501
ENV PORT=8501

# Launch the app on 0.0.0.0
CMD ["streamlit", "run", "streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
