apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: fashion-mnist-job-experiment
  namespace: kubeflow-user-example-com  # 👈 set to your Kubeflow profile namespace
spec:
  objective:
    type: maximize
    goal: 0.90
    objectiveMetricName: accuracy

  algorithm:
    algorithmName: random

  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3

  parameters:
    - name: LEARNING_RATE
      parameterType: double
      feasibleSpace:
        min: "0.0001"
        max: "0.01"
    - name: BATCH_SIZE
      parameterType: int
      feasibleSpace:
        min: "32"
        max: "128"

  trialTemplate:
    primaryContainerName: training-container

    trialParameters:
      - name: LEARNING_RATE
        description: Learning rate for the training job
        reference: LEARNING_RATE
      - name: BATCH_SIZE
        description: Batch size for the training job
        reference: BATCH_SIZE

    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: quay.io/asrivastava98/fashion-mnist-tuner:latest # 👈 set to your Container image
                command:
                  - "python"
                  - "/train.py"
                  - "--learning-rate"
                  - "${trialParameters.LEARNING_RATE}"
                  - "--batch-size"
                  - "${trialParameters.BATCH_SIZE}"
            restartPolicy: Never
