FROM python:3.9-slim

# Install Streamlit and requests
RUN pip install --no-cache-dir streamlit requests

# Copy app
WORKDIR /app
COPY app.py .

# Expose Streamlit default port
EXPOSE 8501

# Entrypoint
ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
